<?php

$LOCAL_LANG = Array (
	'default' => Array (
		'tx_guestbook' => 'Guestbook',
		'tx_guestbook.pi_flexform.sheet_general' => 'General',
		'tx_guestbook.pi_flexform.sheet_template' => 'Template',
		'tx_guestbook.pi_flexform.sheet_form' => 'Form',
		'tx_guestbook.pi_flexform.sheet_list' => 'List & Teaser',
		'tx_guestbook.pi_flexform.what_to_display' => 'What to display:',
		'tx_guestbook.pi_flexform.limit' => 'Limit of entries: ',
		'tx_guestbook.pi_flexform.teasercut' => 'String length of teaser: ',
		'tx_guestbook.pi_flexform.wordcut' => 'Max length of words: ',
		'tx_guestbook.pi_flexform.nolangfilter' => 'Show all languages?',
		'tx_guestbook.pi_flexform.listOrderby' => '"Order by" this field:',
		'tx_guestbook.pi_flexform.ascDesc' => 'Ascending or Descending:',
		'tx_guestbook.pi_flexform.guestbook' => 'Page with guestbook for Teaser and notification mail:',
		'tx_guestbook.pi_flexform.obligation_fields' => 'Obligation Fields:',
		'tx_guestbook.pi_flexform.strip_tags' => 'Strip HTML tags:',
		'tx_guestbook.pi_flexform.email_validation' => 'E-Mail syntax validation:',
		'tx_guestbook.pi_flexform.website_validation' => 'Website validation:',
		'tx_guestbook.pi_flexform.redirect_page' => 'Target page after submitting:',
		'tx_guestbook.pi_flexform.notification_mail' => 'Mail notification after submitting:',
		'tx_guestbook.pi_flexform.whitelist_mail' => 'Mail whitelist (comma separated):',
		'tx_guestbook.pi_flexform.blacklist_mail' => 'Mail blacklist (comma separated):',
		'tx_guestbook.pi_flexform.feedback_mail' => 'Mail to user after submitting:',
		'tx_guestbook.pi_flexform.manual_backend_release' => 'Manual backend release of new entries?',
		'tx_guestbook.pi_flexform.ascDesc_asc' => 'Ascending',
		'tx_guestbook.pi_flexform.ascDesc_desc' => 'Descending',
		'tx_guestbook.pi_flexform.template_file' => 'Template file',
		'tx_guestbook.pi_flexform.recursive' => 'Recursive level selection:',
	),
	'dk' => Array (
		'tx_guestbook' => 'Gæstebog',
		'tx_guestbook.pi_flexform.sheet_general' => 'Standard',
		'tx_guestbook.pi_flexform.sheet_template' => 'Mal',
		'tx_guestbook.pi_flexform.sheet_form' => 'Form',
		'tx_guestbook.pi_flexform.sheet_list' => 'Liste & teaser',
		'tx_guestbook.pi_flexform.what_to_display' => 'Hvad der skal vises:',
		'tx_guestbook.pi_flexform.limit' => 'Begrænsning på indlæg:',
		'tx_guestbook.pi_flexform.teasercut' => 'Tekstlængde på teaser:',
		'tx_guestbook.pi_flexform.listOrderby' => '"Sorter" på dette felt:',
		'tx_guestbook.pi_flexform.ascDesc' => 'Stigende eller faldende:',
		'tx_guestbook.pi_flexform.guestbook' => 'Siden med gæstebogen (bruges af teaser:',
		'tx_guestbook.pi_flexform.obligation_fields' => 'Obligatorisk felt:',
		'tx_guestbook.pi_flexform.strip_tags' => 'Rens for HTML tag:',
		'tx_guestbook.pi_flexform.email_validation' => 'Validering af e-mail syntaks:',
		'tx_guestbook.pi_flexform.website_validation' => 'Validering af hjemmeside:',
		'tx_guestbook.pi_flexform.redirect_page' => 'Når du har sendt, så gå til denne side:',
		'tx_guestbook.pi_flexform.ascDesc_asc' => 'Stigende',
		'tx_guestbook.pi_flexform.ascDesc_desc' => 'Faldende',
		'tx_guestbook.pi_flexform.template_file' => 'Formular',
		'tx_guestbook.pi_flexform.recursive' => 'Valg af underliggende niveau:',
	),
	'de' => Array (
		'tx_guestbook' => 'Gästebuch',
		'tx_guestbook.pi_flexform.sheet_general' => 'Allgemein',
		'tx_guestbook.pi_flexform.sheet_template' => 'Template',
		'tx_guestbook.pi_flexform.sheet_form' => 'Formular',
		'tx_guestbook.pi_flexform.sheet_list' => 'Liste & Teaser',
		'tx_guestbook.pi_flexform.what_to_display' => 'Was soll angezeigt werden?',
		'tx_guestbook.pi_flexform.limit' => 'Wieviele Einträge? ',
		'tx_guestbook.pi_flexform.teasercut' => 'Zeichenlänge des Teasers:',
		'tx_guestbook.pi_flexform.wordcut' => 'Maximale Länge von Wörtern: ',
		'tx_guestbook.pi_flexform.nolangfilter' => 'Alle Sprachen anzeigen?',
		'tx_guestbook.pi_flexform.listOrderby' => 'Sortierung nach diesem Feld:',
		'tx_guestbook.pi_flexform.ascDesc' => 'Aufsteigend oder Absteigend?',
		'tx_guestbook.pi_flexform.guestbook' => 'Seite mit Gästebuch (für Teaser und E-Mail):',
		'tx_guestbook.pi_flexform.obligation_fields' => 'Pflichtfelder:',
		'tx_guestbook.pi_flexform.strip_tags' => 'HTML-Tags entfernen?',
		'tx_guestbook.pi_flexform.email_validation' => 'E-Mail validieren?',
		'tx_guestbook.pi_flexform.website_validation' => 'Website überprüfen?',
		'tx_guestbook.pi_flexform.redirect_page' => 'Zielseite nach Eintrag:',
		'tx_guestbook.pi_flexform.notification_mail' => 'E-Mail-Benachrichtigung nach Eintrag:',
		'tx_guestbook.pi_flexform.whitelist_mail' => 'Mail Whitelist (Kommagetrennt):',
		'tx_guestbook.pi_flexform.blacklist_mail' => 'Mail Blacklist (Kommagetrennt):',
		'tx_guestbook.pi_flexform.feedback_mail' => 'E-Mail an Benutzer nach Eintrag:',
		'tx_guestbook.pi_flexform.manual_backend_release' => 'Manuelle Freigabe von neuen Einträgen?',
		'tx_guestbook.pi_flexform.ascDesc_asc' => 'Aufsteigend',
		'tx_guestbook.pi_flexform.ascDesc_desc' => 'Absteigend',
		'tx_guestbook.pi_flexform.template_file' => 'Template',
		'tx_guestbook.pi_flexform.recursive' => 'Level:',
	),
	'no' => Array (
		'tx_guestbook' => 'Gjestebok',
		'tx_guestbook.pi_flexform.sheet_general' => 'Standard',
		'tx_guestbook.pi_flexform.sheet_template' => 'Mal',
		'tx_guestbook.pi_flexform.sheet_form' => 'Form',
		'tx_guestbook.pi_flexform.sheet_list' => 'Liste & teaser',
		'tx_guestbook.pi_flexform.what_to_display' => 'Hva som skal vises:',
		'tx_guestbook.pi_flexform.limit' => 'Begrensing på innlegg:',
		'tx_guestbook.pi_flexform.teasercut' => 'Tekstlengde på teaser:',
		'tx_guestbook.pi_flexform.wordcut' => 'Maks lengde med ord:',
		'tx_guestbook.pi_flexform.nolangfilter' => 'Vis alle språk?',
		'tx_guestbook.pi_flexform.listOrderby' => '"Sorter" ved dette feltet:',
		'tx_guestbook.pi_flexform.ascDesc' => 'Stigende eller synkende:',
		'tx_guestbook.pi_flexform.guestbook' => 'Side med gjestebok teaser skal bruke:',
		'tx_guestbook.pi_flexform.obligation_fields' => 'Obligatoriske felt:',
		'tx_guestbook.pi_flexform.strip_tags' => 'Rens HTML tagger:',
		'tx_guestbook.pi_flexform.email_validation' => 'Validering av epost syntaks:',
		'tx_guestbook.pi_flexform.website_validation' => 'Validering av webside:',
		'tx_guestbook.pi_flexform.redirect_page' => 'Målside etter innsending:',
		'tx_guestbook.pi_flexform.notification_mail' => 'Epost melding etter posting',
		'tx_guestbook.pi_flexform.whitelist_mail' => 'Epost hvitliste (kommaseparert)',
		'tx_guestbook.pi_flexform.blacklist_mail' => 'Epost svartliste (kommaseparert)',
		'tx_guestbook.pi_flexform.feedback_mail' => 'Epost til bruker etter posting',
		'tx_guestbook.pi_flexform.manual_backend_release' => 'Manuel BE frigivelse av nye innlegg',
		'tx_guestbook.pi_flexform.ascDesc_asc' => 'Stigende',
		'tx_guestbook.pi_flexform.ascDesc_desc' => 'Synkende',
		'tx_guestbook.pi_flexform.template_file' => 'Mal fil',
		'tx_guestbook.pi_flexform.recursive' => 'Underliggende nivå valg:',
	),
	'it' => Array (
		'tx_guestbook' => 'Guestbook',
		'tx_guestbook.pi_flexform.sheet_general' => 'Generale',
		'tx_guestbook.pi_flexform.sheet_template' => 'Template',
		'tx_guestbook.pi_flexform.sheet_form' => 'Form',
		'tx_guestbook.pi_flexform.sheet_list' => 'Elenco e Teaser',
		'tx_guestbook.pi_flexform.what_to_display' => 'Cosa mostrare:',
		'tx_guestbook.pi_flexform.limit' => 'Limite degli inserimenti:',
		'tx_guestbook.pi_flexform.teasercut' => 'Lunghezza del teaser',
		'tx_guestbook.pi_flexform.wordcut' => 'Lunghezza massima delle parole:',
		'tx_guestbook.pi_flexform.nolangfilter' => 'Mostra tutte le lingue?',
		'tx_guestbook.pi_flexform.listOrderby' => '"ordina secondo" questo campo:',
		'tx_guestbook.pi_flexform.ascDesc' => 'Crescente o Decrescente',
		'tx_guestbook.pi_flexform.guestbook' => 'Pagina col guestbook per il Teaser e l\'email di notifica',
		'tx_guestbook.pi_flexform.obligation_fields' => 'Campi Obbligatori',
		'tx_guestbook.pi_flexform.strip_tags' => 'Togli i tag HTML',
		'tx_guestbook.pi_flexform.email_validation' => 'Validazione email',
		'tx_guestbook.pi_flexform.website_validation' => 'Validazione sito web',
		'tx_guestbook.pi_flexform.redirect_page' => 'Pagina di destinazione dopo l\'inserimento',
		'tx_guestbook.pi_flexform.notification_mail' => 'Email di notifica dopo l\'inserimento',
		'tx_guestbook.pi_flexform.whitelist_mail' => 'Lista degli indirizzi email autorizzati ( separati da virgola )',
		'tx_guestbook.pi_flexform.blacklist_mail' => 'Lista degli indirizzi email non autorizzati ( separati da virgola )',
		'tx_guestbook.pi_flexform.feedback_mail' => 'Invia una email all\'utente dopo l\'inserimento',
		'tx_guestbook.pi_flexform.manual_backend_release' => 'Pubblicazione manuale da backend dei nuovi inserimenti ?',
		'tx_guestbook.pi_flexform.ascDesc_asc' => 'Crescente',
		'tx_guestbook.pi_flexform.ascDesc_desc' => 'Decrescente',
		'tx_guestbook.pi_flexform.template_file' => 'Template File',
		'tx_guestbook.pi_flexform.recursive' => 'Selezione ricorsiva dei livelli',
	),
	'fr' => Array (
	),
	'es' => Array (
	),
	'nl' => Array (
		'tx_guestbook' => 'Gastenboek',
		'tx_guestbook.pi_flexform.sheet_general' => 'Algemeen',
		'tx_guestbook.pi_flexform.sheet_template' => 'Sjabloon',
		'tx_guestbook.pi_flexform.sheet_form' => 'Formulier',
		'tx_guestbook.pi_flexform.sheet_list' => 'Lijst & Teaser',
		'tx_guestbook.pi_flexform.what_to_display' => 'Wat tonen:',
		'tx_guestbook.pi_flexform.limit' => 'Max. aantal berichten:',
		'tx_guestbook.pi_flexform.teasercut' => 'Lengte van de teaserregel: ',
		'tx_guestbook.pi_flexform.listOrderby' => '"Sorteren op" dit veld:',
		'tx_guestbook.pi_flexform.ascDesc' => 'Oplopend of Aflopend:',
		'tx_guestbook.pi_flexform.guestbook' => 'Gastenboekpagina(voor de teaser):',
		'tx_guestbook.pi_flexform.obligation_fields' => 'Verplichte velden:',
		'tx_guestbook.pi_flexform.strip_tags' => 'Verwijder HTML tags:',
		'tx_guestbook.pi_flexform.email_validation' => 'Email syntax validatie:',
		'tx_guestbook.pi_flexform.website_validation' => 'Website validatie:',
		'tx_guestbook.pi_flexform.redirect_page' => 'Doelpagina na verzending:',
		'tx_guestbook.pi_flexform.notification_mail' => 'Email bij een nieuw bericht:',
		'tx_guestbook.pi_flexform.feedback_mail' => 'Email naar de gast:',
		'tx_guestbook.pi_flexform.manual_backend_release' => 'Handmatig nieuwe berichten vrijgeven?',
		'tx_guestbook.pi_flexform.ascDesc_asc' => 'Oplopend',
		'tx_guestbook.pi_flexform.ascDesc_desc' => 'Aflopend',
		'tx_guestbook.pi_flexform.template_file' => 'Sjabloonbestand',
		'tx_guestbook.pi_flexform.recursive' => 'Recursief niveau selectie:',
	),
	'cz' => Array (
		'tx_guestbook' => 'Návštìvní kniha',
	),
	'pl' => Array (
	),
	'si' => Array (
	),
	'fi' => Array (
		'tx_guestbook' => 'Vieraskirja',
		'tx_guestbook.pi_flexform.sheet_general' => 'Yleistä',
		'tx_guestbook.pi_flexform.sheet_template' => 'Mallinne',
		'tx_guestbook.pi_flexform.sheet_form' => 'Lomake',
		'tx_guestbook.pi_flexform.sheet_list' => 'Lista & Houkutin',
		'tx_guestbook.pi_flexform.what_to_display' => 'Mitä näytetään:',
		'tx_guestbook.pi_flexform.limit' => 'Kirjausten rajaus:',
		'tx_guestbook.pi_flexform.teasercut' => 'Houkuttimen pituus:',
		'tx_guestbook.pi_flexform.wordcut' => 'Sanojen maksimi pituus:',
		'tx_guestbook.pi_flexform.listOrderby' => 'Läjittele tämän tiedon mukaan:',
		'tx_guestbook.pi_flexform.ascDesc' => 'Nouseva tai lasekva järjestys:',
		'tx_guestbook.pi_flexform.guestbook' => 'Sivulla vieraskirja on houkutinta varten:',
		'tx_guestbook.pi_flexform.obligation_fields' => 'Pakolliset tiedot:',
		'tx_guestbook.pi_flexform.strip_tags' => 'Poista HTML tagit:',
		'tx_guestbook.pi_flexform.email_validation' => 'Sähköpostiosoitteen syntaksin tarkistus:',
		'tx_guestbook.pi_flexform.website_validation' => 'Korisivuston osoitteen tarkistus:',
		'tx_guestbook.pi_flexform.redirect_page' => 'Kohde sivu jonne siirrytään tallennuksen jälkeen:',
		'tx_guestbook.pi_flexform.notification_mail' => 'Huomautus sähköpostilla talleksen jälkeen:',
		'tx_guestbook.pi_flexform.feedback_mail' => 'Lähetä email käyttäjälle tallennuksen jälkeen:',
		'tx_guestbook.pi_flexform.manual_backend_release' => 'Manuaalinen uusien viestien  vapautus taustatoiminnoista?',
		'tx_guestbook.pi_flexform.ascDesc_asc' => 'Nouseva',
		'tx_guestbook.pi_flexform.ascDesc_desc' => 'Laskeva',
		'tx_guestbook.pi_flexform.template_file' => 'Mallinteen tiedosto',
		'tx_guestbook.pi_flexform.recursive' => 'Rekursiivinen tason valinta:',
	),
	'tr' => Array (
		'tx_guestbook' => 'Ziyaretçi defteri',
		'tx_guestbook.pi_flexform.sheet_general' => 'Genel',
		'tx_guestbook.pi_flexform.sheet_template' => 'Þablon',
		'tx_guestbook.pi_flexform.sheet_form' => 'Formül',
		'tx_guestbook.pi_flexform.sheet_list' => 'Liste & Teaser',
		'tx_guestbook.pi_flexform.what_to_display' => 'Görüntülenecekler:',
		'tx_guestbook.pi_flexform.limit' => 'Girdilerin sýnýrý:',
		'tx_guestbook.pi_flexform.teasercut' => 'Teaserin uzunluðu:',
		'tx_guestbook.pi_flexform.wordcut' => 'Kelimelerin max. uzunlu:',
		'tx_guestbook.pi_flexform.nolangfilter' => 'Tüm diller gösterilsinmi?',
		'tx_guestbook.pi_flexform.listOrderby' => 'Sýralamayý þu alan ile yap:',
		'tx_guestbook.pi_flexform.ascDesc' => 'Artan veya azalan:',
		'tx_guestbook.pi_flexform.guestbook' => 'Teaser ve e-posta uyarý mesajý için ziyaretçi defterini içeren sayfa:',
		'tx_guestbook.pi_flexform.obligation_fields' => 'Zorunlu alanlar:',
		'tx_guestbook.pi_flexform.strip_tags' => 'Soyulacak HTML tag\'leri',
		'tx_guestbook.pi_flexform.email_validation' => 'E-posta sözdizim onaylama:',
		'tx_guestbook.pi_flexform.website_validation' => 'Website onaylama:',
		'tx_guestbook.pi_flexform.redirect_page' => 'Gönderiden sonra hedef sayfa:',
		'tx_guestbook.pi_flexform.notification_mail' => 'Gönderiden sonra e-posta uyarý mesajý:',
		'tx_guestbook.pi_flexform.whitelist_mail' => 'E-posta ak liste (virgül ile ayýrýlmýþ)',
		'tx_guestbook.pi_flexform.blacklist_mail' => 'E-posta kara liste (virgül ile ayýrýlmýþ)',
		'tx_guestbook.pi_flexform.feedback_mail' => 'Gönderiden sonra kullanýcýya e-posta mesajý:',
		'tx_guestbook.pi_flexform.manual_backend_release' => 'Arka planda elle yeni kayýtlar yayýnlansýnmý?',
		'tx_guestbook.pi_flexform.ascDesc_asc' => 'Artan',
		'tx_guestbook.pi_flexform.ascDesc_desc' => 'Azalan',
		'tx_guestbook.pi_flexform.template_file' => 'Þablon dosyasý',
		'tx_guestbook.pi_flexform.recursive' => 'Özyineli seviye seçimi:',
	),
	'se' => Array (
		'tx_guestbook' => 'Gästbok',
		'tx_guestbook.pi_flexform.sheet_general' => 'Allmänt',
		'tx_guestbook.pi_flexform.sheet_template' => 'Modell',
		'tx_guestbook.pi_flexform.sheet_form' => 'Formulär',
		'tx_guestbook.pi_flexform.sheet_list' => 'Lista och ingress',
		'tx_guestbook.pi_flexform.what_to_display' => 'Vad skall visas:',
		'tx_guestbook.pi_flexform.limit' => 'Begränsningar:',
		'tx_guestbook.pi_flexform.teasercut' => 'Ingressens längd:',
		'tx_guestbook.pi_flexform.listOrderby' => '"Arrangera enligt" detta fält:',
		'tx_guestbook.pi_flexform.ascDesc' => 'Stigande eller sjunkande',
		'tx_guestbook.pi_flexform.guestbook' => 'Sida med gästbokens ingress',
		'tx_guestbook.pi_flexform.obligation_fields' => 'Nödvändiga fält:',
		'tx_guestbook.pi_flexform.strip_tags' => 'Ta bort HTML-taggar:',
		'tx_guestbook.pi_flexform.email_validation' => 'Epost kontroll:',
		'tx_guestbook.pi_flexform.website_validation' => 'Hemsideskontroll:',
		'tx_guestbook.pi_flexform.redirect_page' => 'Sida efter sändning:',
		'tx_guestbook.pi_flexform.ascDesc_asc' => 'Stigande',
		'tx_guestbook.pi_flexform.ascDesc_desc' => 'Sjunkande',
		'tx_guestbook.pi_flexform.template_file' => 'Modellfil (template)',
		'tx_guestbook.pi_flexform.recursive' => 'Välj nivå bakåt:',
	),
	'pt' => Array (
	),
	'ru' => Array (
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
	),
	'hu' => Array (
		'tx_guestbook' => 'Vendégkönyv',
		'tx_guestbook.pi_flexform.sheet_general' => 'Általános',
		'tx_guestbook.pi_flexform.sheet_template' => 'Sablon',
		'tx_guestbook.pi_flexform.sheet_form' => 'Ûrlap',
		'tx_guestbook.pi_flexform.sheet_list' => 'Lista & Új üzenetek ablak',
		'tx_guestbook.pi_flexform.what_to_display' => 'Mit jelenítsen meg:',
		'tx_guestbook.pi_flexform.limit' => 'Bejegyzési korlát:',
		'tx_guestbook.pi_flexform.teasercut' => 'Új üzenetek ablak karakterhossza:',
		'tx_guestbook.pi_flexform.listOrderby' => '"Rendezd" ezen mezõ szerint:',
		'tx_guestbook.pi_flexform.ascDesc' => 'Növekvõ vagy Csökkenõ:',
		'tx_guestbook.pi_flexform.guestbook' => 'Vendégkönyv oldal az Új üzenetek ablak és az értesítõ email számára:',
		'tx_guestbook.pi_flexform.obligation_fields' => 'Kötelezõ mezõk:',
		'tx_guestbook.pi_flexform.strip_tags' => 'HTML tag-ek kiszûrése:',
		'tx_guestbook.pi_flexform.email_validation' => 'E-Mail ellenõrzés szintakszisa:',
		'tx_guestbook.pi_flexform.website_validation' => 'Weboldal ellenõrzés:',
		'tx_guestbook.pi_flexform.redirect_page' => 'Elküldés utáni céloldal:',
		'tx_guestbook.pi_flexform.notification_mail' => 'Elküldés utáni e-mail értesítés:',
		'tx_guestbook.pi_flexform.manual_backend_release' => 'Új bejegyzések kézi jóváhagyása?',
		'tx_guestbook.pi_flexform.ascDesc_asc' => 'Növekvõ',
		'tx_guestbook.pi_flexform.ascDesc_desc' => 'Csökkenõ',
		'tx_guestbook.pi_flexform.template_file' => 'Sablon fájl',
		'tx_guestbook.pi_flexform.recursive' => 'Rekurzív szintválasztás:',
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
		'tx_guestbook' => 'Livro de visitas',
		'tx_guestbook.pi_flexform.sheet_general' => 'Geral',
		'tx_guestbook.pi_flexform.sheet_template' => 'Modelo',
		'tx_guestbook.pi_flexform.sheet_form' => 'Formulário',
		'tx_guestbook.pi_flexform.sheet_list' => 'Lista & Chamada',
		'tx_guestbook.pi_flexform.what_to_display' => 'O que exibir:',
		'tx_guestbook.pi_flexform.limit' => 'Limite de entradas:',
		'tx_guestbook.pi_flexform.teasercut' => 'Tamanho limite da chamada:',
		'tx_guestbook.pi_flexform.wordcut' => 'Tamanho máximo das palavras:',
		'tx_guestbook.pi_flexform.listOrderby' => '"Ordenar por" este campo:',
		'tx_guestbook.pi_flexform.ascDesc' => 'Ascendente ou Descrescente:',
		'tx_guestbook.pi_flexform.guestbook' => 'Página que contém o livro de visitas para a Chamada e noticiação via e-mail:',
		'tx_guestbook.pi_flexform.obligation_fields' => 'Campos obrigatórios:',
		'tx_guestbook.pi_flexform.strip_tags' => 'Remove tags HTML:',
		'tx_guestbook.pi_flexform.email_validation' => 'Sintaxe de validação de e-mail:',
		'tx_guestbook.pi_flexform.website_validation' => 'Validação de website:',
		'tx_guestbook.pi_flexform.redirect_page' => 'Página de destino após envio:',
		'tx_guestbook.pi_flexform.notification_mail' => 'Notificação por email após envio:',
		'tx_guestbook.pi_flexform.feedback_mail' => 'Enviar email para usuário após envio:',
		'tx_guestbook.pi_flexform.manual_backend_release' => 'Disponibilização manual no backend de novas entradas?',
		'tx_guestbook.pi_flexform.ascDesc_asc' => 'Ascendendo',
		'tx_guestbook.pi_flexform.ascDesc_desc' => 'Descrescendo',
		'tx_guestbook.pi_flexform.template_file' => 'Arquivo de modelo',
		'tx_guestbook.pi_flexform.recursive' => 'Nível de seleção recursiva:',
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
	'eo' => Array (
	),
	'my' => Array (
	),
	'hi' => Array (
	),
);
?>